[package]
name = "toy-macros"
description = "a simple test bed & example vermouth macro"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/soqb/vermouth"
publish = false

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
vermouth = { workspace = true, features = ["warnings", "parse"] }
