[package]
name = "many-literals-upstream"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/soqb/vermouth"
publish = false

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
vermouth = { path = "../../../../", default-features = false, features = ["quote"], optional = true }
quote = { version = "1.0.42", optional = true }

[features]
default = ["vermouth"]
vermouth = ["dep:vermouth"]
dtolnay = ["dep:quote"]
