[package]
name = "much-nesting"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/soqb/vermouth"
publish = false

[dependencies]
upstream = { path = "upstream", package = "much-nesting-upstream", default-features = false }

[features]
vermouth = ["upstream/vermouth"]
dtolnay = ["upstream/dtolnay"]
