[package]
name = "many-literals"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/soqb/vermouth"
publish = false

[dependencies]
upstream = { path = "upstream", package = "many-literals-upstream", default-features = false }

[features]
default = ["vermouth", "dtolnay"]
vermouth = ["upstream/vermouth"]
dtolnay = ["upstream/dtolnay"]

[package.metadata.cargo-all-features]
skip_feature_sets = [
    ["vermouth", "dtolnay"]
]
